language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-19.1.0
    - android-19
    - extra

before_script:
  - sudo apt-get update 
  - sudo apt-get install gcc-4.6 g++-4.6 
  - sudo apt-get install tree cmake gcc-4.6-arm-linux-gnueabi g++-4.6-arm-linux-gnueabi libc6-dev-i386 lib32stdc++6 g++-multilib g++-4.6-multilib
  - sudo apt-get install binutils-mingw-w64-i686 binutils-mingw-w64-x86-64 binutils-mingw-w64  gcc-mingw-w64-i686 g++-mingw-w64-i686
  - mkdir build
  - cd build

  # build for x86_64
  - cmake -Dx86_64=ON .. 
  - make
  - cp ./source/main/testkit-stub ../dest/x86_64/
  - rm -rf *

  # build for i386
  - cmake -Di386=ON .. 
  - make
  - cp ./source/main/testkit-stub ../dest/i386/
  - rm -rf *

  # build for arm
  - cmake -D CMAKE_TOOLCHAIN_FILE=../arm_toolchain.cmake ..
  - make
  - cp ./source/main/testkit-stub ../dest/arm/
  - rm -rf *

  # build for Win32 with MinGW
  - ../tools/prepare_pthread.sh 
  - cmake -D win32=ON -D GNU_HOST=i686-w64-mingw32 -D CMAKE_TOOLCHAIN_FILE=../mingw_cross_toolchain.cmake ..
  - make
  - cp ./source/main/testkit-stub.exe ../dest/windows/
  - rm -rf *

  # build for android
  - cd ../tools 
  - ./install_android_ndk.sh

  ## build PIE binary
  - cd ../android/jni/
  - cp ./Android_PIE.mk ./Android.mk
  - ../../android-ndk/ndk-build clean
  - rm -rf ../libs/*
  - ../../android-ndk/ndk-build
  - cd ../ 
  # build apk
  - gradlew build --stacktrace
  - cp -r build/outputs/apk ../dest/android_PIE/
  - cd .. 

  ## build non-PIE binary
  - cd ./android/jni/
  - cp ./Android_non_PIE.mk ./Android.mk
  - ../../android-ndk/ndk-build clean
  - rm -rf ../libs/*
  - ../../android-ndk/ndk-build
  - cd ../ 
  # build apk
  - gradlew build --stacktrace
  - cp -r build/outputs/apk ../dest/android_non_PIE/
  - cd ..

script: 
  - tree dest/ 
  - tar -cvzf testkit-stub.tar.gz ./dest/

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: G6JJkJ6ok1mc5XGsN5fvKd0V0Kw3oLBDeBqc+AG/tW9drbY/LRC6FQ1s25dbMZySYtEiOquwngnRMDCpyyxU3ekhCetLhzwlS4lITh8jpeCMDdBML+kYYuwMmAIzGJ8LNUwaonXUWHZytTOWlScT+rOH6eKCIKcf27oGDlWH4K4=
  file: ./testkit-stub.tar.gz
  on:
    repo: testkit/testkit-stub
    tags: true
    all_branches: true
